import Entorno.Conexion;
import com.sun.jdi.connect.spi.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import vehiculos.Carro;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ambiente 209-1
 */
public class FrmCrearCarro extends javax.swing.JFrame {
  private static HashMap<String, Carro> listaCarro = new HashMap<>();
  Conexion con = new Conexion();
  Connection cn = con.conectar();
    /**
     * Creates new form NewJFrame
     */
    public FrmCrearCarro() {
      this.listaCarro = FrmMenuCarro.getListaCarro();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labeMarca = new javax.swing.JLabel();
        labeColor = new javax.swing.JLabel();
        labeSerial = new javax.swing.JLabel();
        labeModelo = new javax.swing.JLabel();
        TxtMarca = new javax.swing.JTextField();
        TxtColor = new javax.swing.JTextField();
        TxtSerial = new javax.swing.JTextField();
        TxtModelo = new javax.swing.JTextField();
        btnCrear = new javax.swing.JToggleButton();
        btnLimpiar = new javax.swing.JToggleButton();
        btnVolver = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Crear carro");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        labeMarca.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labeMarca.setText("Marca");
        jPanel2.add(labeMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        labeColor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labeColor.setText("Color");
        jPanel2.add(labeColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        labeSerial.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labeSerial.setText("Serial");
        jPanel2.add(labeSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        labeModelo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labeModelo.setText("Modelo");
        jPanel2.add(labeModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        TxtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMarcaActionPerformed(evt);
            }
        });
        jPanel2.add(TxtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 190, -1));
        jPanel2.add(TxtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 190, -1));
        jPanel2.add(TxtSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 190, -1));
        jPanel2.add(TxtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 180, -1));

        btnCrear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.setPreferredSize(new java.awt.Dimension(120, 40));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel2.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLimpiar.setText("Limpiar ");
        btnLimpiar.setPreferredSize(new java.awt.Dimension(120, 40));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setPreferredSize(new java.awt.Dimension(120, 40));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back-view-of-blue-sedan-on-the-road.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 460));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
 Carro nuevoCarro = new Carro(); 
         nuevoCarro.setModelo (Integer.parseInt(this.TxtModelo.getText()));
         nuevoCarro.setSerial  (Integer.parseInt(this.TxtSerial.getText()));
         nuevoCarro.setColor (this.TxtColor.getText());
         nuevoCarro.setMarca(TxtMarca.getText());
         try {
         PreparedStatement ps = cn.prepareStatement("INSERT INTO carros(serila;marca;modelo;color;estado)VALUES(?,?,?,?,?)");
         ps.setlnt(1, nuevoCarro.getSerial());
         ps.setString(2, nuevoCarro.getMarca());
         ps.settlnt(3,nuevoCarro.getModelo());
         ps.setString(4, nuevoCarro.getColor());
         ps.setString(5, "A");
         ps.excuteUpdate();                
         //listaCarro.put(String.valueOf(nuevoCarro.getSerial()),nuevoCarro);
         JOptionPane.showMessageDialog(null,"Carro agregado a la BD");
         this.btnLimpiar.doClick();        
         } catch (Exception e){
         JOptionPane.showMessageDialog(null,e.getMessage());
  
         }
         
         
         
         
        /* System.out.println("modelo: " + modelo);
         System.out.println("serial: " + Serial);
         System.out.println("color: " + Color);
         System.out.println("marca: " + Marca);*/
         
         
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
         
         this.setVisible(false);
        new FrmMenuCarro().setVisible(true);
        FrmMenuCarro.setListaCarro(listaCarro);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.TxtModelo.setText("");
        this.TxtSerial.setText("");
        this.TxtColor.setText("");
        this.TxtMarca.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void TxtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMarcaActionPerformed
        // TODO add your handling code h
    }//GEN-LAST:event_TxtMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCrearCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCrearCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCrearCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCrearCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCrearCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtColor;
    private javax.swing.JTextField TxtMarca;
    private javax.swing.JTextField TxtModelo;
    private javax.swing.JTextField TxtSerial;
    private javax.swing.JToggleButton btnCrear;
    private javax.swing.JToggleButton btnLimpiar;
    private javax.swing.JToggleButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labeColor;
    private javax.swing.JLabel labeMarca;
    private javax.swing.JLabel labeModelo;
    private javax.swing.JLabel labeSerial;
    // End of variables declaration//GEN-END:variables

    private static class listaCarro {

        private static void put(String valueOf, Carro nuevoCarro) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public listaCarro() {
        }
    }
}
