
import java.util.HashMap;
import javax.swing.JOptionPane;
import vehiculos.Moto;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ambiente 209-1
 */
public class FrmCrearMoto extends javax.swing.JFrame {
static HashMap<String, Moto> listaMotos = new HashMap<>();
    /**
     * Creates new form FrmCrearMoto
     */
    public FrmCrearMoto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtColor = new javax.swing.JTextField();
        TxtMarca = new javax.swing.JTextField();
        TxtSerial = new javax.swing.JTextField();
        TxtModelo = new javax.swing.JTextField();
        onCrear = new javax.swing.JToggleButton();
        onLimpiar = new javax.swing.JToggleButton();
        onVolver = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Modelo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Serial");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Marca");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Color");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setText("Crear Moto");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 60));
        jPanel1.add(TxtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 180, -1));
        jPanel1.add(TxtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 180, -1));
        jPanel1.add(TxtSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 180, -1));

        TxtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtModeloActionPerformed(evt);
            }
        });
        jPanel1.add(TxtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 180, -1));

        onCrear.setText("Crear");
        onCrear.setPreferredSize(new java.awt.Dimension(111, 60));
        onCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCrearActionPerformed(evt);
            }
        });
        jPanel1.add(onCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        onLimpiar.setText("Limpiar");
        onLimpiar.setPreferredSize(new java.awt.Dimension(111, 60));
        onLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(onLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        onVolver.setText("Volver");
        onVolver.setPreferredSize(new java.awt.Dimension(111, 60));
        onVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onVolverActionPerformed(evt);
            }
        });
        jPanel1.add(onVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtModeloActionPerformed

    private void onCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCrearActionPerformed
 Moto nuevoMoto = new Moto(); 
         nuevoMoto.setModelo (Integer.parseInt(this.TxtModelo.getText()));
         nuevoMoto.setSerial  (Integer.parseInt(this.TxtSerial.getText()));
         nuevoMoto.setColor (this.TxtColor.getText());
         nuevoMoto.setMarca(TxtMarca.getText());
         listaMotos.put(String.valueOf(nuevoMoto.getSerial()),nuevoMoto);
         JOptionPane.showMessageDialog(null,"Carro agregado a la BD");
         this.onLimpiar.doClick();       
    }//GEN-LAST:event_onCrearActionPerformed

    private void onVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MenuMoto().setVisible(true);
    }//GEN-LAST:event_onVolverActionPerformed

    private void onLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLimpiarActionPerformed
        // TODO add your handling code here:
        this.TxtModelo.setText("");
        this.TxtSerial.setText("");
        this.TxtColor.setText("");
        this.TxtMarca.setText("");
    }//GEN-LAST:event_onLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCrearMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCrearMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCrearMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCrearMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCrearMoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtColor;
    private javax.swing.JTextField TxtMarca;
    private javax.swing.JTextField TxtModelo;
    private javax.swing.JTextField TxtSerial;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton onCrear;
    private javax.swing.JToggleButton onLimpiar;
    private javax.swing.JToggleButton onVolver;
    // End of variables declaration//GEN-END:variables
}
