
import Entorno.Conexion;
import com.sun.jdi.connect.spi.Connection;
import java.beans.Statement;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import vehiculos.Carro;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Ambiente 209-1
 */
public class FrmListarCarro extends javax.swing.JFrame {

    private static HashMap<String, Carro> listaCarro = new HashMap<>();
    Conexion con = new Conexion ();
    Connection cn = con.conectar();
    /**
     * Creates new form FrmListarCarro
     */
    public FrmListarCarro() {
        initComponents();
        listaCarro = FrmMenuCarro.getListaCarro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarro = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel1.setText("Lista de Carro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 250, 50));

        jTableCarro.setBackground(new java.awt.Color(204, 204, 204));
        jTableCarro.setFont(new java.awt.Font("Segoe UI Light", 2, 12)); // NOI18N
        jTableCarro.setForeground(new java.awt.Color(255, 255, 255));
        jTableCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serial", "Color", "Marca ", "Modelo"
            }
        ));
        jScrollPane1.setViewportView(jTableCarro);
        if (jTableCarro.getColumnModel().getColumnCount() > 0) {
            jTableCarro.getColumnModel().getColumn(0).setResizable(false);
            jTableCarro.getColumnModel().getColumn(1).setResizable(false);
            jTableCarro.getColumnModel().getColumn(2).setResizable(false);
            jTableCarro.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 300));

        btnListar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel1.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 160, 50));

        btnVolver.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnVolver.setText("Volver ");
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        DefaultTableModel modeloCarro = new DefaultTableModel();
        modeloCarro.addColumn("Serial");
        modeloCarro.addColumn("Marca");
        modeloCarro.addColumn("Color");
        modeloCarro.addColumn("Modelo");
        jTableCarro.setModel(modeloCarro);

        Statement st;
        ResultSet rs;
        
        try {
            st = cn.createStatement();
            rs = st.executeQuery("SELECT*FROM carros");
            while (rs.next()){
            System.out.println(rs.getString("serial"));
        }
        } catch (Exception e) {
            System.out.println("Error"+ egetMessage());
        }
        
      //  Iterator<String> carros = listaCarro.keySet().iterator();

    //    while (carros.hasNext()) {
            String serial = carros.next();
            Carro carrito = listaCarro.get(serial);
            
            modeloCarro.addRow(new Object[]{carrito.getSerial(),carrito.getMarca(),carrito.getModelo(),carrito.getColor()});
        }
        jTableCarro.setModel(modeloCarro);

// TODO add your handling code here:
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListarCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCarro;
    // End of variables declaration//GEN-END:variables
}
