/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ambiente 209-1
 */
public class MenuMoto extends javax.swing.JFrame {

    /**
     * Creates new form MenuMoto
     */
    public MenuMoto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        onMoto = new javax.swing.JToggleButton();
        onBuscar = new javax.swing.JToggleButton();
        onModificar = new javax.swing.JToggleButton();
        onEliminar = new javax.swing.JToggleButton();
        onLista = new javax.swing.JToggleButton();
        onSalir = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("MENU MOTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        onMoto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        onMoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/motorcycle.png"))); // NOI18N
        onMoto.setText("Moto");
        onMoto.setPreferredSize(new java.awt.Dimension(150, 80));
        onMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onMotoActionPerformed(evt);
            }
        });
        jPanel1.add(onMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        onBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        onBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        onBuscar.setText("Buscar");
        onBuscar.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel1.add(onBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        onModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        onModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pen-edit.png"))); // NOI18N
        onModificar.setText("Modificar");
        onModificar.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel1.add(onModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, -1));

        onEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        onEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        onEliminar.setText("Eliminar");
        onEliminar.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel1.add(onEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 170, -1));

        onLista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        onLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/file.png"))); // NOI18N
        onLista.setText("Lista");
        onLista.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel1.add(onLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        onSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        onSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/log-out.png"))); // NOI18N
        onSalir.setText("Salir");
        onSalir.setPreferredSize(new java.awt.Dimension(150, 80));
        onSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSalirActionPerformed(evt);
            }
        });
        jPanel1.add(onSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FrmConcencionario().setVisible(true);
    }//GEN-LAST:event_onSalirActionPerformed

    private void onMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onMotoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FrmCrearMoto().setVisible(true);
    }//GEN-LAST:event_onMotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton onBuscar;
    private javax.swing.JToggleButton onEliminar;
    private javax.swing.JToggleButton onLista;
    private javax.swing.JToggleButton onModificar;
    private javax.swing.JToggleButton onMoto;
    private javax.swing.JToggleButton onSalir;
    // End of variables declaration//GEN-END:variables
}
